name: Hexo CICD
on:
  push:
    branches:
    - master
jobs:
  deploy:
    name: hexo build & deploy
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: Build and Deploy
      uses: theme-keep/hexo-deploy-github-pages-action@master # 使用专门部署 Hexo 到 GitHub pages 的 action
      env:
        PERSONAL_TOKEN: ${{ secrets.HEXO_DEPLOY }} # secret 名
        PUBLISH_REPOSITORY: deepincn/blog.deepincn.org # 公共仓库，格式：GitHub 用户名/仓库名
        BRANCH: gh-pages # 分支，填 gh-pages 就行
        PUBLISH_DIR: ./public # 部署 public 目录下的文件
